spring:
  application:
    name: demo
  ##DB 
  jpa:
    hibernate:
      ddl-auto: update ##테이블이 이미 존재하는 경우에 변경사항 적용 ## 들여쓰기 주의
      ##ddl-auto: create ##테이블 자동생성
      open-in-view: false 
      show-sql: true
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/lms_local
    username: root
    password: root123




    
#    thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
#    mode: HTML
#    cache: false
